# -*- coding: utf-8 -*-
#: settings for liquidluck

#: site information
#: all variables can be accessed in template with ``site`` namespace.
#: for instance: {{site.name}}
site:
    name: AraleJS # your module name
    url: "http://aralejs.org/"

#: this config defined information of your site
#: 1. where the resources  2. how should the site be generated
config:
    source: .
    output: _site
    static: _site/static
    static_prefix: /static/
    permalink: "{{folder}}/{{filename}}.html"
    relative_url: true


author:
    default: lepture
    vars:
        # key: value

#: active readers
reader:
    active:
        - iframe.MarkdownReader
    vars:
        post_class: chiang.ChiangPost

#: active writers
writer:
    active:
        - chiang.IframeWriter
        - chiang.PackageWriter
        - chiang.TestWriter
        - liquidluck.writers.core.PostWriter
        - liquidluck.writers.core.StaticWriter
        - liquidluck.writers.core.FileWriter

#: theme variables
theme:
    name: arale2
